#!/usr/bin/env node

const {Client, Intents} = require('discord.js');
const {config} = require('dotenv');
const cron = require('node-cron');
config();

const client = new Client({
	intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MEMBERS, Intents.FLAGS.GUILD_PRESENCES]
});

client.once('ready', () => {
	// run every hour
	const task = cron.schedule('0 * * * *', () => setNicknames(client));
	task.start();
	console.log(`Logged in as ${client.user.tag}`);
});

client.login(process.env.TOKEN);

function setNicknames(client) {
	console.log(new Date().toUTCString() + ': Setting nicknames');

	client.guilds.cache.forEach((g) => {
		g.members.cache.forEach(async (m) => {
			if (m.user.bot || m.guild.ownerId === m.user.id) return;

			const role = m.roles.cache.find((r) => r.name.startsWith('tz='));
			if (role) {
				const tz = role.name.split('=')[1];
				const hourOffset = parseInt(tz.split(':')[0].replace('UTC', ''));
				const minuteOffset = parseInt(tz.split(':')[1]);

				const hour = (new Date().getUTCHours() + parseFloat(hourOffset)) % 24;
				const min = (new Date().getUTCMinutes() + parseFloat(minuteOffset)) % 60;

				const currentTime = `${hour > 9 ? '' : '0'}${hour}:${min}`;
				await m.setNickname(`${m.displayName.split('|')[0]} | ${currentTime}`);
			} else console.error(`Failed to find timezone role for ${m.user.tag} in ${g.name}`);
		});
	});

	console.log('done ----------\n\n');
}
